name: Cache Nginx CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cache-nginx-ci.yaml
      - cache-nginx/**
env:
  IMAGE: ghcr.io/cloudwebmanage/cwm-cdn-api-cache-nginx
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: cache-nginx
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache-latest
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache-latest,mode=max
