name: Cache Nginx CI
on:
  push:
    paths:
      - .github/workflows/cache-nginx-ci.yaml
      - cache-nginx/**
      - tests/test_cache_nginx*
env:
  UV_VERSION: 0.8.8
  PYTHON_VERSION: "3.12"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}
      - uses: CloudWebManage/cwm-iac/actions/docker-build-push@main
        with:
          test_script: |
            uv sync
            E2E=yes uv run pytest tests/test_cache_nginx.py
          image_suffix: cwm-cdn-api-cache-nginx
          context: cache-nginx
          dockerfile: cache-nginx/Dockerfile
          deploy_key_b64: ${{ secrets.CWM_WORKER_CLUSTER_DEPLOY_KEY_B64 }}
          deploy_file_path: config/auto-updated/cwm-cdn-api/cache-nginx.yaml
          deploy_content_template: |
            cwmCdnApi:
              cacheNginx:
                image: "__IMAGE__"
          deploy_commit_message: "Update cwm-cdn-api/cache-nginx"
