name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/nginx-ci.yaml
      - tenant-nginx/**
      - tests/test_tenant_nginx*
      - .github/workflows/cache-nginx-ci.yaml
      - cache-nginx/**
      - tests/test_cache_nginx*
env:
  IMAGE: ghcr.io/cloudwebmanage/cwm-cdn-api
  # should match the versions in Dockerfile
  UV_VERSION: 0.8.8
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}
      - name: run tests
        run: |
          uv sync
          E2E=yes uv run pytest
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache-latest
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache-latest,mode=max
          build-args: |
            VERSION=${{ github.sha }}
      - name: update cwm-worker-cluster
        env:
          DEPLOY_KEY_B64: ${{ secrets.CWM_WORKER_CLUSTER_DEPLOY_KEY_B64 }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo $DEPLOY_KEY_B64 | base64 -d > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          export GIT_SSH_COMMAND="ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@localhost"
          git clone git@github.com:CloudWebManage/cwm-worker-cluster.git
          cd cwm-worker-cluster
          echo 'cwmCdnApi:
            api:
              image: "'$IMAGE':'${GITHUB_SHA}'"
          ' > config/auto-updated/cwm-cdn-api/api.yaml
          git add config/auto-updated/cwm-cdn-api/api.yaml
          git commit -m "Update cwm-cdn-api/api"
          git push origin main
