name: Nginx CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nginx-ci.yaml
      - tenant-nginx/**
      - tests/test_tenant_nginx*
env:
  IMAGE: ghcr.io/cloudwebmanage/cwm-cdn-api-tenant-nginx
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          pip install pytest==8.4.2 &&\
          E2E=yes pytest tests/test_tenant_nginx.py
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: tenant-nginx
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache-latest
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache-latest,mode=max
